---
name: 'nahcnuj.work'
template_engine: mustache
theme: default
language: ja
host_url: https://www.nahcnuj.work
years: '2020'
author: 'Junichi Hayashi'
contact_list:
  - title: Twitter
    href: https://twitter.com/nahcnuj
    address: '@nahcnuj'
  - title: Facebook
    href: https://www.facebook.com/nahcnuj
    address: '{{ site.author }}'
  - title: Email
    href: '#'
    address: nahcnuj.work [at] gmail.com
